/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/flows': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Flows
     * @description Every ``.py`` file in the workspace, with when it changed and how it last ran.
     */
    get: operations['listFlows'];
    put?: never;
    /**
     * Create Flow
     * @description Write a new flow from a template or from a model, and return it parsed.
     */
    post: operations['createFlow'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/flows/parse': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Parse Flow
     * @description Read source that is not saved yet: the model, or why it is code-only.
     */
    post: operations['parseFlow'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/flows/generate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Generate Flow
     * @description The Python for a model. Pure text: nothing is imported or run.
     */
    post: operations['generateFlow'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/flows/{path}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Flow
     * @description One flow: its source, its model or why it is code-only, its graph and layout.
     */
    get: operations['getFlow'];
    /**
     * Save Flow
     * @description Write a flow. A ``modified`` that no longer matches answers 409 with the file.
     */
    put: operations['saveFlow'];
    post?: never;
    /**
     * Delete Flow
     * @description Delete a flow and its sidecar.
     */
    delete: operations['deleteFlow'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/flows/{path}/layout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Save Layout
     * @description Write the canvas sidecar next to the flow.
     */
    put: operations['saveLayout'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/flows/{path}/rename': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Rename Flow
     * @description Move a flow and its sidecar.
     */
    post: operations['renameFlow'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/flows/{path}/check': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Check Flow
     * @description ``tq.check`` in a child process: the counts, or the GraphError as it stands.
     */
    post: operations['checkFlow'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/flows/{path}/explain': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Explain Flow
     * @description ``tq.explain``: one line per node and edge.
     */
    post: operations['explainFlow'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/flows/{path}/draw': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Draw Flow
     * @description ``tq.draw``: the Mermaid text for the expanded graph.
     */
    post: operations['drawFlow'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/flows/{path}/optimize': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Optimize Flow
     * @description What ``tq.optimize`` would cut: its notes and the graph it leaves.
     */
    post: operations['optimizeFlow'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/runs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Runs
     * @description Runs, newest first. The log is left out here; ask for one run, or its log.
     */
    get: operations['listRuns'];
    put?: never;
    /**
     * Start Run
     * @description Start a flow in a child process and return the run that was recorded.
     */
    post: operations['startRun'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/runs/{run_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Run */
    get: operations['getRun'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/runs/{run_id}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cancel Run
     * @description SIGTERM now, SIGKILL after ``cancel_grace``. A run that ended is returned as is.
     */
    post: operations['cancelRun'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/runs/{run_id}/log': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Run Log
     * @description What the flow printed, live while it runs and from the store afterwards.
     */
    get: operations['getRunLog'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/runs/{run_id}/trace': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Run Trace
     * @description The Chrome trace file, for a run started with ``trace``.
     */
    get: operations['getRunTrace'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/schedules': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Schedules */
    get: operations['listSchedules'];
    put?: never;
    /**
     * Create Schedule
     * @description Add a schedule. The cron expression is checked before anything is stored.
     */
    post: operations['createSchedule'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/schedules/{schedule_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Schedule */
    put: operations['updateSchedule'];
    post?: never;
    /** Delete Schedule */
    delete: operations['deleteSchedule'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/schedules/preview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Preview Schedule
     * @description What an expression means, and the next five times it fires.
     */
    post: operations['previewSchedule'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/schedules/{schedule_id}/run': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Run Schedule Now
     * @description Fire a schedule now, the way the scheduler would.
     */
    post: operations['runScheduleNow'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Settings
     * @description Everything the settings page shows. Keys are reported as set, never echoed.
     */
    get: operations['getSettings'];
    /**
     * Update Settings
     * @description Change any subset. ``ai.anthropic_key`` and ``ai.openai_key`` go to the key file.
     */
    put: operations['updateSettings'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/ai/chat': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Ai Chat
     * @description The builder, as an event stream: its words, its tool calls, the flow it wrote.
     */
    post: operations['aiChat'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Is the server up, and what is it working on?
     */
    get: operations['getHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AiSettings */
    AiSettings: {
      /** Provider */
      provider: string;
      /** Model */
      model?: string | null;
      /** Has Anthropic Key */
      has_anthropic_key: boolean;
      /** Has Openai Key */
      has_openai_key: boolean;
    };
    /** ChatMessage */
    ChatMessage: {
      /** Role */
      role: string;
      /** Content */
      content: string;
    };
    /** ChatRequest */
    ChatRequest: {
      /** Path */
      path?: string | null;
      /** Messages */
      messages: components['schemas']['ChatMessage'][];
      /** Provider */
      provider?: string | null;
      /** Model */
      model?: string | null;
      /** Sample */
      sample?: string | null;
    };
    /** CheckResult */
    CheckResult: {
      /** Ok */
      ok: boolean;
      /** Nodes */
      nodes: number;
      /** Edges */
      edges: number;
    };
    /** CronPreview */
    CronPreview: {
      /** Description */
      description: string;
      /** Next Five */
      next_five: string[];
    };
    /** CronPreviewRequest */
    CronPreviewRequest: {
      /** Cron */
      cron: string;
    };
    /** DrawResult */
    DrawResult: {
      /** Mermaid */
      mermaid: string;
    };
    /** ExplainResult */
    ExplainResult: {
      /** Text */
      text: string;
    };
    /** FlowDetail */
    FlowDetail: {
      /** Path */
      path: string;
      /** Source */
      source: string;
      /** Modified */
      modified: string;
      /** Model */
      model?: {
        [key: string]: unknown;
      } | null;
      /** Code Only */
      code_only?: {
        [key: string]: unknown;
      } | null;
      /** Graph */
      graph?: {
        [key: string]: unknown;
      } | null;
      /** Layout */
      layout?: {
        [key: string]: unknown;
      } | null;
    };
    /** FlowList */
    FlowList: {
      /** Workspace */
      workspace: string;
      /** Flows */
      flows: components['schemas']['FlowSummary'][];
    };
    /** FlowSummary */
    FlowSummary: {
      /** Path */
      path: string;
      /** Name */
      name: string;
      /** Modified */
      modified: string;
      /** Size */
      size: number;
      /** Has Layout */
      has_layout: boolean;
      /** Last Run */
      last_run?: {
        [key: string]: unknown;
      } | null;
    };
    /** GenerateRequest */
    GenerateRequest: {
      /** Model */
      model: {
        [key: string]: unknown;
      };
    };
    /** GenerateResult */
    GenerateResult: {
      /** Source */
      source: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** Health */
    Health: {
      /** Ok */
      ok: boolean;
      /** Version */
      version: string;
      /** Workspace */
      workspace: string;
      /** Runs Live */
      runs_live: number;
      /** Scheduler */
      scheduler: boolean;
    };
    /** NewFlow */
    NewFlow: {
      /** Path */
      path: string;
      /**
       * Template
       * @default empty
       */
      template:
        | string
        | {
            [key: string]: unknown;
          };
    };
    /** NewSchedule */
    NewSchedule: {
      /** Flow */
      flow: string;
      /** Cron */
      cron: string;
      /** Sample */
      sample?: string | null;
      /** Runtime */
      runtime?: string | null;
      /**
       * Enabled
       * @default true
       */
      enabled: boolean;
    };
    /** Ok */
    Ok: {
      /**
       * Ok
       * @default true
       */
      ok: boolean;
    };
    /** OptimizeRequest */
    OptimizeRequest: {
      /**
       * All2All
       * @default false
       */
      all2all: boolean;
    };
    /** OptimizeResult */
    OptimizeResult: {
      /**
       * Source
       * @description the rewrite has no Python form yet; run with optimize=true instead
       */
      source?: string | null;
      /** Notes */
      notes: string[];
      /** Graph */
      graph?: {
        [key: string]: unknown;
      } | null;
    };
    /** ParseRequest */
    ParseRequest: {
      /** Source */
      source: string;
      /**
       * Name
       * @default flow
       */
      name: string;
    };
    /** ParseResult */
    ParseResult: {
      /** Model */
      model?: {
        [key: string]: unknown;
      } | null;
      /** Code Only */
      code_only?: {
        [key: string]: unknown;
      } | null;
      /** Graph */
      graph?: {
        [key: string]: unknown;
      } | null;
    };
    /** RenameFlow */
    RenameFlow: {
      /** Path */
      path: string;
    };
    /** RunList */
    RunList: {
      /** Runs */
      runs: components['schemas']['RunModel'][];
    };
    /** RunModel */
    RunModel: {
      /** Id */
      id: number;
      /** Flow */
      flow: string;
      /** Runtime */
      runtime: string;
      /** Sample */
      sample?: string | null;
      /** Trigger */
      trigger: string;
      /** Started */
      started: string;
      /** Ended */
      ended?: string | null;
      /** Status */
      status: string;
      /** Report */
      report?: {
        [key: string]: unknown;
      } | null;
      /**
       * Log
       * @default
       */
      log: string;
      /** Trace Path */
      trace_path?: string | null;
      /** Error */
      error?: string | null;
      /**
       * Live
       * @default false
       */
      live: boolean;
    };
    /** SaveFlow */
    SaveFlow: {
      /** Source */
      source: string;
      /**
       * Modified
       * @description the `modified` you were given; a mismatch answers 409
       */
      modified?: string | null;
    };
    /** ScheduleChange */
    ScheduleChange: {
      /** Flow */
      flow?: string | null;
      /** Cron */
      cron?: string | null;
      /** Sample */
      sample?: string | null;
      /** Runtime */
      runtime?: string | null;
      /** Enabled */
      enabled?: boolean | null;
    };
    /** ScheduleList */
    ScheduleList: {
      /** Schedules */
      schedules: components['schemas']['ScheduleModel'][];
    };
    /** ScheduleModel */
    ScheduleModel: {
      /** Id */
      id: number;
      /** Flow */
      flow: string;
      /** Cron */
      cron: string;
      /** Sample */
      sample?: string | null;
      /** Runtime */
      runtime: string;
      /** Enabled */
      enabled: boolean;
      /** Created */
      created: string;
      /** Last Run */
      last_run?: number | null;
      /** Last Status */
      last_status?: string | null;
      /** Next Run */
      next_run?: string | null;
      /** Description */
      description: string;
      /** Next Five */
      next_five: string[];
    };
    /** ServerSettings */
    ServerSettings: {
      /** Host */
      host: string;
      /** Port */
      port: number;
      /** Token Set */
      token_set: boolean;
    };
    /** SettingsModel */
    SettingsModel: {
      /** Workspace */
      workspace: string;
      /** Default Runtime */
      default_runtime: string;
      /** Default Batch */
      default_batch: number;
      /** Exec Timeout */
      exec_timeout: number;
      /** Max Concurrent Runs */
      max_concurrent_runs: number;
      /** Max Source Bytes */
      max_source_bytes: number;
      /** Cancel Grace */
      cancel_grace: number;
      /** Keep Traces Days */
      keep_traces_days: number;
      /** Theme */
      theme: string;
      ai: components['schemas']['AiSettings'];
      server: components['schemas']['ServerSettings'];
    };
    /** StartRun */
    StartRun: {
      /** Path */
      path: string;
      /** Runtime */
      runtime?: string | null;
      /** Sample */
      sample?: string | null;
      /** Batch */
      batch?: number | null;
      /**
       * Tap
       * @default 0
       */
      tap: number;
      /**
       * Trace
       * @default false
       */
      trace: boolean;
      /**
       * Optimize
       * @default false
       */
      optimize: boolean;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listFlows: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FlowList'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  createFlow: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NewFlow'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FlowDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  parseFlow: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ParseRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ParseResult'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  generateFlow: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GenerateRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GenerateResult'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  getFlow: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FlowDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  saveFlow: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        path: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SaveFlow'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FlowDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  deleteFlow: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Ok'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  saveLayout: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        path: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Ok'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  renameFlow: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        path: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RenameFlow'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FlowDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  checkFlow: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CheckResult'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  explainFlow: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExplainResult'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  drawFlow: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DrawResult'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  optimizeFlow: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        path: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['OptimizeRequest'] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OptimizeResult'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  listRuns: {
    parameters: {
      query?: {
        flow?: string | null;
        limit?: number;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RunList'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  startRun: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StartRun'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RunModel'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  getRun: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RunModel'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  cancelRun: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RunModel'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  getRunLog: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/plain': string;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  getRunTrace: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  listSchedules: {
    parameters: {
      query?: {
        flow?: string | null;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ScheduleList'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  createSchedule: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NewSchedule'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ScheduleModel'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  updateSchedule: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        schedule_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ScheduleChange'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ScheduleModel'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  deleteSchedule: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        schedule_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Ok'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  previewSchedule: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CronPreviewRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CronPreview'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  runScheduleNow: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        schedule_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RunModel'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  getSettings: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SettingsModel'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  updateSettings: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SettingsModel'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  aiChat: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChatRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  getHealth: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Health'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
