/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/workspace/history': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Workspace History
     * @description Is this workspace in a git repository, and how much of it is uncommitted?
     */
    get: operations['getWorkspaceHistory'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspace/history/init': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Init Workspace History
     * @description ``git init`` here, with a ``.gitignore`` that leaves the server's own files out.
     */
    post: operations['initWorkspaceHistory'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/flows/{path}/history/{rev}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Flow Version
     * @description One old version of a flow, and how it differs from the file as it is now.
     */
    get: operations['getFlowVersion'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/flows/{path}/history': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Flow History
     * @description The commits that touched this flow, newest first, and whether it has changed.
     */
    get: operations['getFlowHistory'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/flows/{path}/restore': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Restore Flow
     * @description Put a flow, and its sidecar, back as they were. Nothing is committed.
     */
    post: operations['restoreFlow'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/flows': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Flows
     * @description Every ``.py`` file in the workspace, with when it changed and how it last ran.
     */
    get: operations['listFlows'];
    put?: never;
    /**
     * Create Flow
     * @description Write a new flow from a template or from a model, and return it parsed.
     */
    post: operations['createFlow'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/flows/parse': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Parse Flow
     * @description Read source that is not saved yet: the model, or why it is code-only.
     */
    post: operations['parseFlow'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/flows/generate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Generate Flow
     * @description The Python for a model. Pure text: nothing is imported or run.
     */
    post: operations['generateFlow'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/flows/{path}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Flow
     * @description One flow: its source, its model or why it is code-only, its graph and layout.
     */
    get: operations['getFlow'];
    /**
     * Save Flow
     * @description Write a flow. A ``modified`` that no longer matches answers 409 with the file.
     *
     *     ``commit`` asks for the save to be committed with that message, and the
     *     ``auto_commit`` setting asks for every save to be. A commit that was asked for
     *     explicitly is checked before anything is written: a workspace with no repository
     *     answers 400 with the file untouched, rather than saving and quietly not committing.
     */
    put: operations['saveFlow'];
    post?: never;
    /**
     * Delete Flow
     * @description Delete a flow and its sidecar.
     */
    delete: operations['deleteFlow'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/flows/{path}/layout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Save Layout
     * @description Write the canvas sidecar next to the flow.
     */
    put: operations['saveLayout'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/flows/{path}/rename': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Rename Flow
     * @description Move a flow and its sidecar.
     */
    post: operations['renameFlow'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/flows/{path}/check': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Check Flow
     * @description ``tq.check`` in a child process: the counts, or the GraphError as it stands.
     *
     *     The imports are probed first, with the interpreter the run would use, and travel
     *     with the failure as well as with the success: a flow that does not check because
     *     ``import pandas`` fails is exactly the one whose Problems panel needs the ``pip
     *     install`` line.
     */
    post: operations['checkFlow'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/flows/{path}/explain': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Explain Flow
     * @description ``tq.explain``: one line per node and edge.
     */
    post: operations['explainFlow'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/flows/{path}/draw': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Draw Flow
     * @description ``tq.draw``: the Mermaid text for the expanded graph.
     */
    post: operations['drawFlow'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/flows/{path}/optimize': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Optimize Flow
     * @description What ``tq.optimize`` would cut: its notes and the graph it leaves.
     */
    post: operations['optimizeFlow'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/runs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Runs
     * @description Runs, newest first. The log is left out here; ask for one run, or its log.
     */
    get: operations['listRuns'];
    put?: never;
    /**
     * Start Run
     * @description Start a flow in a child process and return the run that was recorded.
     */
    post: operations['startRun'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/runs/{run_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Run */
    get: operations['getRun'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/runs/{run_id}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cancel Run
     * @description SIGTERM now, SIGKILL after ``cancel_grace``. A run that ended is returned as is.
     */
    post: operations['cancelRun'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/runs/{run_id}/log': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Run Log
     * @description What the flow printed, live while it runs and from the store afterwards.
     */
    get: operations['getRunLog'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/runs/{run_id}/trace': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Run Trace
     * @description The Chrome trace file, for a run started with ``trace``.
     */
    get: operations['getRunTrace'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/runs/{run_id}/notifications': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Run Notifications
     * @description Every attempt to tell somebody about this run, sent or failed, oldest first.
     */
    get: operations['getRunNotifications'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/schedules': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Schedules */
    get: operations['listSchedules'];
    put?: never;
    /**
     * Create Schedule
     * @description Add a schedule. The cron expression is checked before anything is stored.
     */
    post: operations['createSchedule'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/schedules/{schedule_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Schedule */
    put: operations['updateSchedule'];
    post?: never;
    /** Delete Schedule */
    delete: operations['deleteSchedule'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/schedules/preview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Preview Schedule
     * @description What an expression means, and the next five times it fires.
     */
    post: operations['previewSchedule'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/schedules/{schedule_id}/run': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Run Schedule Now
     * @description Fire a schedule now, the way the scheduler would.
     */
    post: operations['runScheduleNow'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/schedules/{schedule_id}/test': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Test Schedule
     * @description Send this schedule's notifications now, and say what each channel answered.
     *
     *     The message is the real one, with ``event`` set to ``test`` and the schedule's
     *     last run in it when it has had one. Delivery is not retried here: somebody is
     *     waiting for the answer, and a webhook that is down should say so in ten seconds
     *     rather than in forty.
     */
    post: operations['testScheduleNotifications'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login
     * @description Sign in. The session token comes back once; it is stored only as a sha256.
     */
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Logout
     * @description Forget this session. A token that is not a session has nothing to forget.
     */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Whoami
     * @description Who the caller is and what kind of server this is: the page's first question.
     */
    get: operations['whoami'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/setup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Setup First Admin
     * @description Make the first administrator, from the login page of a ``--token`` server.
     */
    post: operations['setupFirstAdmin'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Change Password
     * @description Change your own password. Sessions live on: this is the browser that asked.
     */
    post: operations['changePassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/tokens': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Tokens
     * @description Your API tokens. The tokens themselves are not kept, so they are not here.
     */
    get: operations['listApiTokens'];
    put?: never;
    /**
     * Create Token
     * @description Make an API token for scripts. It never expires and is shown this once.
     */
    post: operations['createApiToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/tokens/{token_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Token
     * @description Take one of your API tokens back. Anything using it stops working at once.
     */
    delete: operations['deleteApiToken'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Users
     * @description Everybody who can sign in, with when each was last seen.
     */
    get: operations['listUsers'];
    put?: never;
    /**
     * Create User
     * @description Add a user with a password they are asked to change at their first sign-in.
     */
    post: operations['createUser'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users/{user_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Update User
     * @description Change a role, disable an account, or set a password the user must change.
     */
    put: operations['updateUser'];
    post?: never;
    /**
     * Delete User
     * @description Remove a user, and with them every session and token they had.
     */
    delete: operations['deleteUser'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Settings
     * @description Everything the settings page shows. Keys are reported as set, never echoed.
     *
     *     A member sees the workspace and the run settings; whether a key is set, and the
     *     address the server listens on, are an administrator's business.
     */
    get: operations['getSettings'];
    /**
     * Update Settings
     * @description Change any subset. The three secrets -- ``ai.anthropic_key``, ``ai.openai_key``
     *     and ``notifications.smtp_password`` -- go to the key file, never to the store.
     */
    put: operations['updateSettings'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/ai/chat': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Ai Chat
     * @description The builder, as an event stream: its words, its tool calls, the flow it wrote.
     */
    post: operations['aiChat'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Is the server up, and what is it working on?
     *
     *     No login: this is what a monitor and a login page both ask. Where the workspace
     *     is on disk is not a stranger's business, so it is left out until someone signs in.
     */
    get: operations['getHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AiSettings */
    AiSettings: {
      /** Provider */
      provider: string;
      /** Model */
      model?: string | null;
      /**
       * Has Anthropic Key
       * @description null: not an admin
       */
      has_anthropic_key?: boolean | null;
      /**
       * Has Openai Key
       * @description null: not an admin
       */
      has_openai_key?: boolean | null;
    };
    /** ChatMessage */
    ChatMessage: {
      /** Role */
      role: string;
      /** Content */
      content: string;
    };
    /** ChatRequest */
    ChatRequest: {
      /** Path */
      path?: string | null;
      /** Messages */
      messages: components['schemas']['ChatMessage'][];
      /** Provider */
      provider?: string | null;
      /** Model */
      model?: string | null;
      /** Sample */
      sample?: string | null;
    };
    /** CheckResult */
    CheckResult: {
      /** Ok */
      ok: boolean;
      /** Nodes */
      nodes: number;
      /** Edges */
      edges: number;
      /**
       * Imports
       * @description what the flow imports and whether the run interpreter has it
       */
      imports?: components['schemas']['ImportProbe'][];
    };
    /** CommitMessage */
    CommitMessage: {
      /**
       * Message
       * @default
       */
      message: string;
    };
    /** Committed */
    Committed: {
      /** Rev */
      rev: string;
      /** Short */
      short: string;
    };
    /** CronPreview */
    CronPreview: {
      /** Description */
      description: string;
      /** Next Five */
      next_five: string[];
    };
    /** CronPreviewRequest */
    CronPreviewRequest: {
      /** Cron */
      cron: string;
    };
    /** DeliveryModel */
    DeliveryModel: {
      /** Channel */
      channel: string;
      /** Target */
      target: string;
      /** Status */
      status: string;
      /** Error */
      error?: string | null;
    };
    /** DrawResult */
    DrawResult: {
      /** Mermaid */
      mermaid: string;
    };
    /** ExplainResult */
    ExplainResult: {
      /** Text */
      text: string;
    };
    /** FlowDetail */
    FlowDetail: {
      /** Path */
      path: string;
      /** Source */
      source: string;
      /** Modified */
      modified: string;
      /** Model */
      model?: {
        [key: string]: unknown;
      } | null;
      /** Code Only */
      code_only?: {
        [key: string]: unknown;
      } | null;
      /** Graph */
      graph?: {
        [key: string]: unknown;
      } | null;
      /** Layout */
      layout?: {
        [key: string]: unknown;
      } | null;
      /** @description the commit this save made, when it made one */
      commit?: components['schemas']['Committed'] | null;
    };
    /** FlowList */
    FlowList: {
      /** Workspace */
      workspace: string;
      /** Flows */
      flows: components['schemas']['FlowSummary'][];
    };
    /** FlowSummary */
    FlowSummary: {
      /** Path */
      path: string;
      /** Name */
      name: string;
      /** Modified */
      modified: string;
      /** Size */
      size: number;
      /** Has Layout */
      has_layout: boolean;
      /** Last Run */
      last_run?: {
        [key: string]: unknown;
      } | null;
    };
    /** GenerateRequest */
    GenerateRequest: {
      /** Model */
      model: {
        [key: string]: unknown;
      };
    };
    /** GenerateResult */
    GenerateResult: {
      /** Source */
      source: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** Health */
    Health: {
      /** Ok */
      ok: boolean;
      /** Version */
      version: string;
      /**
       * Workspace
       * @description left out when the caller is not signed in
       */
      workspace?: string | null;
      /** Runs Live */
      runs_live: number;
      /** Scheduler */
      scheduler: boolean;
    };
    /** HistoryEntry */
    HistoryEntry: {
      /** Rev */
      rev: string;
      /** Short */
      short: string;
      /** Author */
      author: string;
      /** Date */
      date: string;
      /** Message */
      message: string;
      /**
       * Head
       * @default false
       */
      head: boolean;
    };
    /** HistoryList */
    HistoryList: {
      /** Entries */
      entries: components['schemas']['HistoryEntry'][];
      /**
       * Uncommitted
       * @default false
       */
      uncommitted: boolean;
    };
    /** HistoryStatus */
    HistoryStatus: {
      /** Available */
      available: boolean;
      /** Reason */
      reason?: string | null;
      /**
       * Repo
       * @default false
       */
      repo: boolean;
      /** Root */
      root?: string | null;
      /**
       * Dirty
       * @default 0
       */
      dirty: number;
    };
    /** HistoryVersion */
    HistoryVersion: {
      /** Rev */
      rev: string;
      /** Source */
      source: string;
      /** Diff */
      diff: string;
    };
    /** ImportProbe */
    ImportProbe: {
      /** Module */
      module: string;
      /** Ok */
      ok: boolean;
      /** Hint */
      hint?: string | null;
    };
    /** IssuedToken */
    IssuedToken: {
      /** Id */
      id: number;
      /**
       * Token
       * @description shown once; only its sha256 is kept
       */
      token: string;
      /**
       * Label
       * @default
       */
      label: string;
    };
    /** LastOutcome */
    LastOutcome: {
      /** Status */
      status: string;
      /** Attempts */
      attempts: number;
      /** Notified */
      notified: boolean;
    };
    /** LoginRequest */
    LoginRequest: {
      /** Name */
      name: string;
      /** Password */
      password: string;
    };
    /** LoginResult */
    LoginResult: {
      /**
       * Token
       * @description the session token; it is not shown again
       */
      token: string;
      user: components['schemas']['UserModel'];
    };
    /** MeResult */
    MeResult: {
      user?: components['schemas']['UserModel'] | null;
      /**
       * Mode
       * @description local | users | token
       */
      mode: string;
      /**
       * Can Setup
       * @default false
       */
      can_setup: boolean;
      /**
       * Note
       * @description A line the login page shows, from TOLQUANE_WEB_LOGIN_NOTE: a demo's credentials, who to ask for an account.
       */
      note?: string | null;
    };
    /** NewFlow */
    NewFlow: {
      /** Path */
      path: string;
      /**
       * Template
       * @default empty
       */
      template:
        | string
        | {
            [key: string]: unknown;
          };
    };
    /** NewSchedule */
    NewSchedule: {
      /** Flow */
      flow: string;
      /** Cron */
      cron: string;
      /** Sample */
      sample?: string | null;
      /** Runtime */
      runtime?: string | null;
      /**
       * Enabled
       * @default true
       */
      enabled: boolean;
      /** Params */
      params?: {
        [key: string]: unknown;
      };
      /** Env */
      env?: {
        [key: string]: string;
      };
      notify?: components['schemas']['Notify'] | null;
      /**
       * Retries
       * @default 0
       */
      retries: number;
      /**
       * Retry Delay
       * @default 60
       */
      retry_delay: number;
    };
    /** NewToken */
    NewToken: {
      /**
       * Label
       * @default
       */
      label: string;
    };
    /** NewUser */
    NewUser: {
      /** Name */
      name: string;
      /** Password */
      password: string;
      /**
       * Role
       * @default member
       */
      role: string;
    };
    /** NotificationList */
    NotificationList: {
      /** Notifications */
      notifications: components['schemas']['NotificationModel'][];
    };
    /** NotificationModel */
    NotificationModel: {
      /** Id */
      id: number;
      /** Run Id */
      run_id?: number | null;
      /** Schedule Id */
      schedule_id?: number | null;
      /** Channel */
      channel: string;
      /** Target */
      target: string;
      /** Status */
      status: string;
      /** Error */
      error?: string | null;
      /** Created */
      created: string;
    };
    /** NotificationSettings */
    NotificationSettings: {
      /** Webhook Default */
      webhook_default?: string | null;
      smtp?: components['schemas']['SmtpSettings'] | null;
      /**
       * Has Smtp Password
       * @description null: not an admin
       */
      has_smtp_password?: boolean | null;
    };
    /** Notify */
    Notify: {
      /**
       * Events
       * @description failed, deadlock, cancelled, done
       */
      events?: string[];
      /**
       * Webhook
       * @description null: the default from settings
       */
      webhook?: string | null;
      /** Emails */
      emails?: string[];
    };
    /** Ok */
    Ok: {
      /**
       * Ok
       * @default true
       */
      ok: boolean;
    };
    /** OptimizeRequest */
    OptimizeRequest: {
      /**
       * All2All
       * @default false
       */
      all2all: boolean;
    };
    /** OptimizeResult */
    OptimizeResult: {
      /**
       * Source
       * @description the rewrite has no Python form yet; run with optimize=true instead
       */
      source?: string | null;
      /** Notes */
      notes: string[];
      /** Graph */
      graph?: {
        [key: string]: unknown;
      } | null;
    };
    /** ParseRequest */
    ParseRequest: {
      /** Source */
      source: string;
      /**
       * Name
       * @default flow
       */
      name: string;
    };
    /** ParseResult */
    ParseResult: {
      /** Model */
      model?: {
        [key: string]: unknown;
      } | null;
      /** Code Only */
      code_only?: {
        [key: string]: unknown;
      } | null;
      /** Graph */
      graph?: {
        [key: string]: unknown;
      } | null;
    };
    /** PasswordChange */
    PasswordChange: {
      /**
       * Current
       * @default
       */
      current: string;
      /** New */
      new: string;
    };
    /** RenameFlow */
    RenameFlow: {
      /** Path */
      path: string;
    };
    /** RestoreRequest */
    RestoreRequest: {
      /** Rev */
      rev: string;
    };
    /** RunList */
    RunList: {
      /** Runs */
      runs: components['schemas']['RunModel'][];
    };
    /** RunModel */
    RunModel: {
      /** Id */
      id: number;
      /** Flow */
      flow: string;
      /** Runtime */
      runtime: string;
      /** Sample */
      sample?: string | null;
      /** Trigger */
      trigger: string;
      /**
       * User
       * @default local
       */
      user: string;
      /** Started */
      started: string;
      /** Ended */
      ended?: string | null;
      /** Status */
      status: string;
      /** Report */
      report?: {
        [key: string]: unknown;
      } | null;
      /**
       * Log
       * @default
       */
      log: string;
      /** Trace Path */
      trace_path?: string | null;
      /** Error */
      error?: string | null;
      /** Params */
      params?: {
        [key: string]: unknown;
      };
      /** Env */
      env?: {
        [key: string]: string;
      };
      /**
       * Live
       * @default false
       */
      live: boolean;
    };
    /** SaveFlow */
    SaveFlow: {
      /** Source */
      source: string;
      /**
       * Modified
       * @description the `modified` you were given; a mismatch answers 409
       */
      modified?: string | null;
      /** @description commit the file after saving it, with this message */
      commit?: components['schemas']['CommitMessage'] | null;
    };
    /** ScheduleChange */
    ScheduleChange: {
      /** Flow */
      flow?: string | null;
      /** Cron */
      cron?: string | null;
      /** Sample */
      sample?: string | null;
      /** Runtime */
      runtime?: string | null;
      /** Enabled */
      enabled?: boolean | null;
      /** Params */
      params?: {
        [key: string]: unknown;
      } | null;
      /** Env */
      env?: {
        [key: string]: string;
      } | null;
      notify?: components['schemas']['Notify'] | null;
      /** Retries */
      retries?: number | null;
      /** Retry Delay */
      retry_delay?: number | null;
    };
    /** ScheduleList */
    ScheduleList: {
      /** Schedules */
      schedules: components['schemas']['ScheduleModel'][];
    };
    /** ScheduleModel */
    ScheduleModel: {
      /** Id */
      id: number;
      /** Flow */
      flow: string;
      /** Cron */
      cron: string;
      /** Sample */
      sample?: string | null;
      /** Runtime */
      runtime: string;
      /** Enabled */
      enabled: boolean;
      /** Created */
      created: string;
      /**
       * User
       * @default local
       */
      user: string;
      /** Last Run */
      last_run?: number | null;
      /** Last Status */
      last_status?: string | null;
      /** Next Run */
      next_run?: string | null;
      /** Params */
      params?: {
        [key: string]: unknown;
      };
      /** Env */
      env?: {
        [key: string]: string;
      };
      notify?: components['schemas']['Notify'];
      /**
       * Retries
       * @default 0
       */
      retries: number;
      /**
       * Retry Delay
       * @default 60
       */
      retry_delay: number;
      last_outcome?: components['schemas']['LastOutcome'] | null;
      /** Description */
      description: string;
      /** Next Five */
      next_five: string[];
    };
    /** ServerSettings */
    ServerSettings: {
      /** Host */
      host: string;
      /** Port */
      port: number;
      /** Token Set */
      token_set: boolean;
    };
    /** SettingsModel */
    SettingsModel: {
      /** Workspace */
      workspace: string;
      /** Default Runtime */
      default_runtime: string;
      /** Default Batch */
      default_batch: number;
      /** Exec Timeout */
      exec_timeout: number;
      /** Max Concurrent Runs */
      max_concurrent_runs: number;
      /** Max Source Bytes */
      max_source_bytes: number;
      /** Cancel Grace */
      cancel_grace: number;
      /** Keep Traces Days */
      keep_traces_days: number;
      /** Theme */
      theme: string;
      /**
       * Python
       * @description the interpreter runs and one-shot commands use
       */
      python: string;
      /**
       * Auto Commit
       * @default false
       */
      auto_commit: boolean;
      /**
       * Env
       * @description the workspace environment; null: not an admin
       */
      env?: {
        [key: string]: string;
      } | null;
      /**
       * Env Names
       * @description the names of the workspace environment
       */
      env_names?: string[];
      notifications: components['schemas']['NotificationSettings'];
      ai: components['schemas']['AiSettings'];
      /** @description the address and whether a token is set; admins only */
      server?: components['schemas']['ServerSettings'] | null;
    };
    /** SmtpSettings */
    SmtpSettings: {
      /** Host */
      host: string;
      /**
       * Port
       * @default 587
       */
      port: number;
      /**
       * Username
       * @default
       */
      username: string;
      /**
       * From
       * @default
       */
      from: string;
      /**
       * Starttls
       * @default true
       */
      starttls: boolean;
    };
    /** StartRun */
    StartRun: {
      /** Path */
      path: string;
      /** Runtime */
      runtime?: string | null;
      /** Sample */
      sample?: string | null;
      /** Batch */
      batch?: number | null;
      /**
       * Tap
       * @default 0
       */
      tap: number;
      /**
       * Trace
       * @default false
       */
      trace: boolean;
      /**
       * Optimize
       * @default false
       */
      optimize: boolean;
      /**
       * Params
       * @description keywords for the flow's build()
       */
      params?: {
        [key: string]: unknown;
      };
      /**
       * Env
       * @description variables this run's child process gets
       */
      env?: {
        [key: string]: string;
      };
    };
    /** TestResults */
    TestResults: {
      /** Results */
      results: components['schemas']['DeliveryModel'][];
    };
    /** TokenList */
    TokenList: {
      /** Tokens */
      tokens: components['schemas']['TokenModel'][];
    };
    /** TokenModel */
    TokenModel: {
      /** Id */
      id: number;
      /**
       * Label
       * @default
       */
      label: string;
      /** Created */
      created: string;
      /** Last Seen */
      last_seen?: string | null;
    };
    /** UserChange */
    UserChange: {
      /** Role */
      role?: string | null;
      /** Disabled */
      disabled?: boolean | null;
      /** Password */
      password?: string | null;
    };
    /** UserList */
    UserList: {
      /** Users */
      users: components['schemas']['UserModel'][];
    };
    /** UserModel */
    UserModel: {
      /**
       * Id
       * @description 0 for the implicit local admin and for the server token
       */
      id: number;
      /** Name */
      name: string;
      /** Role */
      role: string;
      /**
       * Created
       * @default
       */
      created: string;
      /**
       * Disabled
       * @default false
       */
      disabled: boolean;
      /**
       * Must Change Password
       * @default false
       */
      must_change_password: boolean;
      /** Last Seen */
      last_seen?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getWorkspaceHistory: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HistoryStatus'];
        };
      };
    };
  };
  initWorkspaceHistory: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Ok'];
        };
      };
    };
  };
  getFlowVersion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        path: string;
        rev: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HistoryVersion'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  getFlowHistory: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path: {
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HistoryList'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  restoreFlow: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        path: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RestoreRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FlowDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  listFlows: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FlowList'];
        };
      };
    };
  };
  createFlow: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NewFlow'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FlowDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  parseFlow: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ParseRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ParseResult'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  generateFlow: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GenerateRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GenerateResult'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  getFlow: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FlowDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  saveFlow: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        path: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SaveFlow'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FlowDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  deleteFlow: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Ok'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  saveLayout: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        path: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Ok'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  renameFlow: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        path: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RenameFlow'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FlowDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  checkFlow: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CheckResult'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  explainFlow: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExplainResult'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  drawFlow: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DrawResult'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  optimizeFlow: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        path: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['OptimizeRequest'] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OptimizeResult'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  listRuns: {
    parameters: {
      query?: {
        flow?: string | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RunList'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  startRun: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StartRun'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RunModel'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  getRun: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RunModel'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  cancelRun: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RunModel'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  getRunLog: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/plain': string;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  getRunTrace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  getRunNotifications: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NotificationList'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  listSchedules: {
    parameters: {
      query?: {
        flow?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ScheduleList'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  createSchedule: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NewSchedule'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ScheduleModel'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  updateSchedule: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        schedule_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ScheduleChange'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ScheduleModel'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  deleteSchedule: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        schedule_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Ok'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  previewSchedule: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CronPreviewRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CronPreview'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  runScheduleNow: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        schedule_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RunModel'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  testScheduleNotifications: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        schedule_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TestResults'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LoginResult'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Ok'];
        };
      };
    };
  };
  whoami: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MeResult'];
        };
      };
    };
  };
  setupFirstAdmin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LoginResult'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordChange'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Ok'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  listApiTokens: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenList'];
        };
      };
    };
  };
  createApiToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NewToken'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['IssuedToken'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  deleteApiToken: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Ok'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  listUsers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserList'];
        };
      };
    };
  };
  createUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NewUser'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserModel'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  updateUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserChange'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserModel'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  deleteUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Ok'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  getSettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SettingsModel'];
        };
      };
    };
  };
  updateSettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SettingsModel'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  aiChat: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChatRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Health'];
        };
      };
    };
  };
}
