"""``web/openapi.json`` is the contract the frontend's types are generated from.

It is checked in because the frontend build has no Python: ``npm run api:types`` reads
that file, not a running server. So it has to be regenerated whenever a route changes,
and this test is what says so.

The frontend has the other half of the pair (``web/src/api/schema.test.ts``): it checks
the generated types still match the checked-in document. Between them, a route the
server adds cannot quietly reach the app as ``unknown``.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

pytest.importorskip("fastapi", reason="tolquane web needs the [web] extra")

from tolquane.web.server import create_app
from tolquane.web.settings import AppSettings

ROOT = Path(__file__).resolve().parents[2]
OPENAPI = ROOT / "web" / "openapi.json"

REGENERATE = (
    "web/openapi.json is out of date. Run, from the repository root:\n"
    "    tolquane web --openapi > web/openapi.json\n"
    "then, in web/:\n"
    "    npm run api:types"
)


def live_schema(tmp_path: Path) -> dict[str, Any]:
    """What ``tolquane web --openapi`` prints: the app's own document, nothing started."""
    app = create_app(
        AppSettings(
            workspace=tmp_path,
            db_path=tmp_path / "web.db",
            config_path=tmp_path / "web.toml",
            start_scheduler=False,
        )
    )
    try:
        document: dict[str, Any] = app.openapi()
        return document
    finally:
        app.state.supervisor.shutdown()
        app.state.store.close()


def test_the_checked_in_document_is_the_app(tmp_path: Path) -> None:
    live = live_schema(tmp_path)
    stored = json.loads(OPENAPI.read_text())
    if stored != live:
        paths = set(live["paths"]) ^ set(stored["paths"])
        changed = f" (paths that differ: {sorted(paths)})" if paths else ""
        pytest.fail(f"{REGENERATE}{changed}")


def test_every_route_has_an_operation_id(tmp_path: Path) -> None:
    """The generated wrappers are named after these, so a missing one is a nameless route."""
    live = live_schema(tmp_path)
    missing = [
        f"{method.upper()} {path}"
        for path, methods in live["paths"].items()
        for method, operation in methods.items()
        if not operation.get("operationId")
    ]
    assert not missing, f"routes without an operation_id: {missing}"


def test_the_generated_types_are_checked_in() -> None:
    """`npm run api:types` writes this; the wheel does not need it, a reviewer does."""
    types = ROOT / "web" / "src" / "api" / "schema.d.ts"
    assert types.exists(), REGENERATE
    text = types.read_text()
    assert "auto-generated by openapi-typescript" in text
    stored = json.loads(OPENAPI.read_text())
    named = {
        operation["operationId"]
        for methods in stored["paths"].values()
        for operation in methods.values()
        if operation.get("operationId")
    }
    absent = sorted(name for name in named if f"  {name}: {{" not in text)
    assert not absent, f"schema.d.ts has no types for {absent}\n{REGENERATE}"
